var tail_string = 'を入力して下さい．'

module.exports = {
    isEmail: 'メールアドレス' + tail_string,
    isUrl: 'URL' + tail_string,
    isIP: 'IPアドレス' + tail_string,
    isAlpha: 'アルファベット' + tail_string,
    isAlphanumeric: 'アルファベットか数字' + tail_string,
    isHexadecimal: '16進数' + tail_string,
    isHexColor: '16進数の色' + tail_string,
    isNumeric: '数字' + tail_string,
    isLowercase: '小文字' + tail_string,
    isUppercase: '大文字' + tail_string,
    isInt: '整数値を入力して下さい。',
    isDecimal: '10進数' + tail_string,
    isDivisibleBy: '割り切れる数' + tail_string,
    notNull: 'この項目は必須です．',
    isNull: 'この項目は開けて下さい．',
    notEmpty: 'この項目は必須です．',
    equals: '等しくありません．',
    contains: '含まれていない文字があります．',
    notContains: '含まれてはいけない文字が入っています．',
    regex: '正しくない文字列です．',
    notRegex: '正しくない文字列です．',
    len: '指定の長さ' + tail_string,
    isUUID: '正しいUUIDを入力して下さい',
    isDate: '正しい日付' + tail_string,
    isAfter: '指定の日付より後' + tail_string,
    isBefore: '指定の日付より前' + tail_string,
    isIn: '含まれていない項目があります．',
    notIn: '含まれてはいけない項目が入っています．',
    min: '短すぎます．',
    max: '長過ぎます．',
    isArray: '配列' + tail_string,
    isCreditCard: '正しいクレジットカード番号' + tail_string
};
